"""
Core data structures for the Trading Engine.

Contains base classes and data structures used across the engine.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum
from datetime import datetime
import numpy as np
import pandas as pd


# ============================================================================
# ENUMS
# ============================================================================

class Side(Enum):
    """Order side."""
    BUY = "BUY"
    SELL = "SELL"


# ============================================================================
# DATA CLASSES
# ============================================================================

@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    timestamp: datetime
    side: Side
    price: float
    quantity: float = 1.0
    stop_loss: Optional[float] = None  # Add this line
    take_profit: Optional[float] = None # Optional: for take-profit levels


@dataclass
class Trade:
    """A complete round-trip trade (buy and sell)."""
    entry_time: datetime
    exit_time: Optional[datetime]
    entry_price: float
    exit_price: Optional[float]
    quantity: float = 1.0
    exit_reason: Optional[str] = None  # 'signal', 'stop_loss', 'take_profit', 'end_of_data'
    
    @property
    def pnl(self) -> float:
        """Profit/loss for this trade."""
        if self.exit_price is None:
            return 0.0
        return (self.exit_price - self.entry_price) * self.quantity
    
    @property
    def pnl_pct(self) -> float:
        """Profit/loss as percentage."""
        if self.exit_price is None or self.entry_price == 0:
            return 0.0
        return (self.exit_price - self.entry_price) / self.entry_price
    
    @property
    def is_open(self) -> bool:
        """Whether trade is still open."""
        return self.exit_price is None
    
    @property
    def is_winner(self) -> bool:
        """Whether trade was profitable."""
        return self.pnl > 0


@dataclass
class BacktestResult:
    """Results from running a strategy on a single ticker."""
    ticker: str
    strategy_name: str
    trades: List[Trade] = field(default_factory=list)
    signals: List[Signal] = field(default_factory=list)  # Raw signals from strategy
    prices: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    equity_curve: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    
    # ---- Computed Properties from Trades ----
    
    @property
    def closed_trades(self) -> List[Trade]:
        """All completed trades."""
        return [t for t in self.trades if not t.is_open]
    
    @property
    def open_trades(self) -> List[Trade]:
        """All open trades."""
        return [t for t in self.trades if t.is_open]
    
    @property
    def entry_prices(self) -> np.ndarray:
        """Entry prices of all trades."""
        return np.array([t.entry_price for t in self.trades])
    
    @property
    def exit_prices(self) -> np.ndarray:
        """Exit prices of closed trades."""
        return np.array([t.exit_price for t in self.closed_trades])
    
    # ---- PnL Calculations ----
    
    @property
    def realized_pnl(self) -> float:
        """Profit from closed trades."""
        return sum(t.pnl for t in self.closed_trades)
    
    @property
    def unrealized_pnl(self) -> float:
        """Profit from open positions (marked to last price)."""
        if not self.open_trades or len(self.prices) == 0:
            return 0.0
        last_price = self.prices.iloc[-1]
        return sum((last_price - t.entry_price) * t.quantity for t in self.open_trades)
    
    @property
    def total_pnl(self) -> float:
        """Total profit (realized + unrealized)."""
        return self.realized_pnl + self.unrealized_pnl
    
    @property
    def num_trades(self) -> int:
        """Total number of completed trades."""
        return len(self.closed_trades)
    
    @property
    def win_rate(self) -> float:
        """Percentage of winning trades."""
        closed = self.closed_trades
        if not closed:
            return 0.0
        wins = sum(1 for t in closed if t.is_winner)
        return wins / len(closed)
    
    def build_equity_curve(self) -> pd.Series:
        """Build cumulative PnL curve from trades."""
        equity = pd.Series(0.0, index=self.prices.index)
        
        for trade in self.trades:
            entry_ts = pd.Timestamp(trade.entry_time)
            if entry_ts in equity.index:
                equity.at[entry_ts] -= trade.entry_price * trade.quantity
            
            if trade.exit_time is not None and trade.exit_price is not None:
                exit_ts = pd.Timestamp(trade.exit_time)
                if exit_ts in equity.index:
                    equity.at[exit_ts] += trade.exit_price * trade.quantity
        
        self.equity_curve = equity.cumsum()
        return self.equity_curve


# ============================================================================
# STRATEGY BASE CLASS
# ============================================================================

class Strategy(ABC):
    """Base class for trading strategies.
    
    Strategies generate signals (buy/sell), not complete trades.
    The Engine processes signals and handles stop-loss/take-profit.
    """
    
    def __init__(self, name: str):
        self.name = name
    
    @abstractmethod
    def generate_signals(self, prices: pd.DataFrame, balance: float) -> List[Signal]:
        """Generate trading signals from price data.
        
        Returns a list of Signal objects indicating when to buy/sell.
        """
        pass
    
    @abstractmethod
    def get_params(self) -> Dict[str, Any]:
        """Get strategy parameters."""
        pass
    
    def set_params(self, **kwargs):
        """Set strategy parameters."""
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)
